name: 'Custom Keymap Drawer'
description: 'Use local keymap-drawer version'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install pyyaml pydantic tree-sitter

    - name: Setup local keymap-drawer
      shell: bash
      run: |
        cd ${{ github.workspace }}/.github/actions/keymap-drawer
        pip install -e .
        ln -sf ${{ github.workspace }}/.github/actions/keymap-drawer/keymap_drawer ${{ github.workspace }}/.github/actions/keymap-drawer/keymap_drawer
