manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mpabegg
      url-base: https://github.com/mpabegg
  projects:
    - name: zmk
      remote: mpabegg
      revision: swapper
      import: app/west.yml
  self:
    path: config
